# Generated by Django 4.1.3 on 2022-11-11 13:19

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReactionAvailable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1, unique=True, verbose_name='эмоция')),
            ],
            options={
                'verbose_name': 'реакция',
                'verbose_name_plural': 'реакции',
            },
        ),
        migrations.CreateModel(
            name='ReactionPremium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1, unique=True, verbose_name='эмоция')),
            ],
            options={
                'verbose_name': 'премиум реакция',
                'verbose_name_plural': 'премиум реакции',
            },
        ),
        migrations.CreateModel(
            name='VotingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription', models.BooleanField(default=False, verbose_name='подписка')),
                ('duration_sub', models.IntegerField(blank=True, null=True, verbose_name='длительность подписки')),
                ('duration', models.IntegerField(verbose_name='продолжительность услуги')),
                ('duration_value', models.CharField(choices=[('minute', 'МИНУТ'), ('hour', 'ЧАСОВ')], default='minutes', max_length=55)),
                ('to_start', models.DateTimeField(blank=True, null=True, verbose_name='время начала (в UTC формате)')),
                ('link_channel', models.URLField(max_length=120, verbose_name='ссылка на канал')),
                ('link_post', models.URLField(verbose_name='ссылка на публикацию')),
                ('count', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1, message='Количество должно быть положительным числом')], verbose_name='количество')),
                ('count_done', models.IntegerField(default=0, verbose_name='выполненный объем')),
                ('price', models.IntegerField(default=0, verbose_name='стоимость')),
                ('quick', models.BooleanField(default=False, verbose_name='максимальная скорость')),
                ('viewed', models.BooleanField(default=False, verbose_name='просмотрен')),
                ('done', models.BooleanField(default=False, verbose_name='обработан')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='время создания')),
                ('count_posts', models.IntegerField(blank=True, null=True, verbose_name='количество последних публикаций')),
                ('spread', models.BooleanField(default=False, verbose_name='разброс (5%)')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='email', verbose_name='Заказчик')),
            ],
            options={
                'verbose_name': 'задача (голосование)',
                'verbose_name_plural': 'задачи (голосование)',
            },
        ),
        migrations.CreateModel(
            name='ViewTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription', models.BooleanField(default=False, verbose_name='подписка')),
                ('duration_sub', models.IntegerField(blank=True, null=True, verbose_name='длительность подписки')),
                ('duration', models.IntegerField(verbose_name='продолжительность услуги')),
                ('duration_value', models.CharField(choices=[('minute', 'МИНУТ'), ('hour', 'ЧАСОВ')], default='minutes', max_length=55)),
                ('to_start', models.DateTimeField(blank=True, null=True, verbose_name='время начала (в UTC формате)')),
                ('link_channel', models.URLField(max_length=120, verbose_name='ссылка на канал')),
                ('count', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1, message='Количество должно быть положительным числом')], verbose_name='количество')),
                ('count_done', models.IntegerField(default=0, verbose_name='выполненный объем')),
                ('price', models.IntegerField(default=0, verbose_name='стоимость')),
                ('quick', models.BooleanField(default=False, verbose_name='максимальная скорость')),
                ('viewed', models.BooleanField(default=False, verbose_name='просмотрен')),
                ('done', models.BooleanField(default=False, verbose_name='обработан')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='время создания')),
                ('view_as_sub', models.BooleanField(default=False, verbose_name='читать подписчиками')),
                ('count_posts', models.IntegerField(null=True, verbose_name='кол-во последних публикаций')),
                ('count_post_pday', models.IntegerField(default=0, verbose_name='среднее кол-во публикаций в день для просмотров')),
                ('spread', models.BooleanField(default=False, verbose_name='разброс (5%)')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='email', verbose_name='Заказчик')),
            ],
            options={
                'verbose_name': 'задача (просмотры)',
                'verbose_name_plural': 'задачи (просмотры)',
            },
        ),
        migrations.CreateModel(
            name='SubscribeTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.IntegerField(verbose_name='продолжительность услуги')),
                ('duration_value', models.CharField(choices=[('minute', 'МИНУТ'), ('hour', 'ЧАСОВ')], default='minutes', max_length=55)),
                ('to_start', models.DateTimeField(blank=True, null=True, verbose_name='время начала (в UTC формате)')),
                ('link_channel', models.URLField(max_length=120, verbose_name='ссылка на канал')),
                ('count', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1, message='Количество должно быть положительным числом')], verbose_name='количество')),
                ('count_done', models.IntegerField(default=0, verbose_name='выполненный объем')),
                ('price', models.IntegerField(default=0, verbose_name='стоимость')),
                ('quick', models.BooleanField(default=False, verbose_name='максимальная скорость')),
                ('viewed', models.BooleanField(default=False, verbose_name='просмотрен')),
                ('done', models.BooleanField(default=False, verbose_name='обработан')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='время создания')),
                ('read_last_posts', models.BooleanField(default=False, verbose_name='чтение последних публикаций')),
                ('gender', models.CharField(choices=[('random', 'Случайно'), ('male', 'Мужской'), ('female', 'Женский')], default='random', max_length=120, verbose_name='предпочтительный пол')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='email', verbose_name='Заказчик')),
            ],
            options={
                'verbose_name': 'задача (подписки)',
                'verbose_name_plural': 'задачи (подписки)',
            },
        ),
        migrations.CreateModel(
            name='RepostTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription', models.BooleanField(default=False, verbose_name='подписка')),
                ('duration_sub', models.IntegerField(blank=True, null=True, verbose_name='длительность подписки')),
                ('count', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1, message='Количество должно быть положительным числом')], verbose_name='количество')),
                ('count_done', models.IntegerField(default=0, verbose_name='выполненный объем')),
                ('price', models.IntegerField(default=0, verbose_name='стоимость')),
                ('quick', models.BooleanField(default=False, verbose_name='максимальная скорость')),
                ('viewed', models.BooleanField(default=False, verbose_name='просмотрен')),
                ('done', models.BooleanField(default=False, verbose_name='обработан')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='время создания')),
                ('link_post', models.URLField(verbose_name='ссылка на публикацию')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='email', verbose_name='Заказчик')),
            ],
            options={
                'verbose_name': 'задача (репосты)',
                'verbose_name_plural': 'задачи (репосты)',
            },
        ),
        migrations.CreateModel(
            name='ReactionsTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription', models.BooleanField(default=False, verbose_name='подписка')),
                ('duration_sub', models.IntegerField(blank=True, null=True, verbose_name='длительность подписки')),
                ('duration', models.IntegerField(verbose_name='продолжительность услуги')),
                ('duration_value', models.CharField(choices=[('minute', 'МИНУТ'), ('hour', 'ЧАСОВ')], default='minutes', max_length=55)),
                ('link_channel', models.URLField(max_length=120, verbose_name='ссылка на канал')),
                ('link_posts', models.CharField(max_length=500, verbose_name='сылка на пост, номер поста или интервал постов')),
                ('count', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1, message='Количество должно быть положительным числом')], verbose_name='количество')),
                ('count_done', models.IntegerField(default=0, verbose_name='выполненный объем')),
                ('price', models.IntegerField(default=0, verbose_name='стоимость')),
                ('quick', models.BooleanField(default=False, verbose_name='максимальная скорость')),
                ('viewed', models.BooleanField(default=False, verbose_name='просмотрен')),
                ('done', models.BooleanField(default=False, verbose_name='обработан')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='время создания')),
                ('count_posts', models.IntegerField(blank=True, null=True, verbose_name='количество последних публикаций')),
                ('spread', models.BooleanField(default=False, verbose_name='разброс (5%)')),
                ('link_post', models.URLField(verbose_name='ссылка на публикацию')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='email', verbose_name='Заказчик')),
                ('reactions', models.ManyToManyField(to='service.reactionavailable', verbose_name='реакции')),
                ('reactions_premium', models.ManyToManyField(to='service.reactionpremium', verbose_name='премиум реакции')),
            ],
            options={
                'verbose_name': 'задача (реакции)',
                'verbose_name_plural': 'задачи (реакции)',
            },
        ),
        migrations.CreateModel(
            name='CommentTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_post', models.URLField(verbose_name='ссылка на публикацию')),
                ('count', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1, message='Количество должно быть положительным числом')], verbose_name='количество')),
                ('count_done', models.IntegerField(default=0, verbose_name='выполненный объем')),
                ('price', models.IntegerField(default=0, verbose_name='стоимость')),
                ('quick', models.BooleanField(default=False, verbose_name='максимальная скорость')),
                ('viewed', models.BooleanField(default=False, verbose_name='просмотрен')),
                ('done', models.BooleanField(default=False, verbose_name='обработан')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='время создания')),
                ('comments', models.TextField(verbose_name='комментарии через запятую')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='email', verbose_name='Заказчик')),
            ],
            options={
                'verbose_name': 'задача (комментарии)',
                'verbose_name_plural': 'задачи (комментарии)',
            },
        ),
    ]
