# Generated by Django 4.1.3 on 2022-11-11 14:44

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.IntegerField(verbose_name='продолжительность услуги')),
                ('duration_value', models.CharField(choices=[('minute', 'МИНУТ'), ('hour', 'ЧАСОВ')], default='minutes', max_length=55)),
                ('to_start', models.DateTimeField(blank=True, null=True, verbose_name='время начала (в UTC формате)')),
                ('link_channel', models.URLField(max_length=120, verbose_name='ссылка на канал')),
                ('count', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1, message='Количество должно быть положительным числом')], verbose_name='количество')),
                ('count_done', models.IntegerField(default=0, verbose_name='выполненный объем')),
                ('price', models.IntegerField(default=0, verbose_name='стоимость')),
                ('quick', models.BooleanField(default=False, verbose_name='максимальная скорость')),
                ('viewed', models.BooleanField(default=False, verbose_name='просмотрен')),
                ('done', models.BooleanField(default=False, verbose_name='обработан')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='время создания')),
                ('read_last_posts', models.BooleanField(default=False, verbose_name='чтение последних публикаций')),
                ('gender', models.CharField(choices=[('random', 'Случайно'), ('male', 'Мужской'), ('female', 'Женский')], default='random', max_length=120, verbose_name='предпочтительный пол')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks_subscriptions', to=settings.AUTH_USER_MODEL, to_field='email', verbose_name='Заказчик')),
            ],
            options={
                'verbose_name': 'задача (подписки)',
                'verbose_name_plural': 'задачи (подписки)',
            },
        ),
        migrations.AlterField(
            model_name='commenttask',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks_comments', to=settings.AUTH_USER_MODEL, to_field='email', verbose_name='Заказчик'),
        ),
        migrations.AlterField(
            model_name='reactionstask',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks_reactions', to=settings.AUTH_USER_MODEL, to_field='email', verbose_name='Заказчик'),
        ),
        migrations.AlterField(
            model_name='reposttask',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks_reposts', to=settings.AUTH_USER_MODEL, to_field='email', verbose_name='Заказчик'),
        ),
        migrations.AlterField(
            model_name='viewtask',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks_views', to=settings.AUTH_USER_MODEL, to_field='email', verbose_name='Заказчик'),
        ),
        migrations.AlterField(
            model_name='votingtask',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks_voting', to=settings.AUTH_USER_MODEL, to_field='email', verbose_name='Заказчик'),
        ),
        migrations.DeleteModel(
            name='SubscribeTask',
        ),
    ]
