# Generated by Django 4.1.3 on 2022-11-11 14:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_subscriptiontask_alter_commenttask_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='votingtask',
            name='number_button',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, message='Номер кнопки не может быть отрицательным')], verbose_name='Порядковый № кнопки'),
        ),
    ]
