# Generated by Django 4.1.3 on 2022-11-11 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_votingtask_number_button'),
    ]

    operations = [
        migrations.AddField(
            model_name='reactionstask',
            name='count_post_pday',
            field=models.IntegerField(default=0, verbose_name='среднее кол-во публикаций в день'),
        ),
        migrations.AddField(
            model_name='reposttask',
            name='count_post_pday',
            field=models.IntegerField(default=0, verbose_name='среднее кол-во публикаций в день'),
        ),
        migrations.AddField(
            model_name='votingtask',
            name='count_post_pday',
            field=models.IntegerField(default=0, verbose_name='среднее кол-во публикаций в день'),
        ),
        migrations.AlterField(
            model_name='viewtask',
            name='count_post_pday',
            field=models.IntegerField(default=0, verbose_name='среднее кол-во публикаций в день'),
        ),
    ]
