# Generated by Django 4.1.3 on 2022-11-11 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_reactionstask_count_post_pday_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reactionstask',
            name='count_post_pday',
        ),
        migrations.RemoveField(
            model_name='reposttask',
            name='count_post_pday',
        ),
        migrations.RemoveField(
            model_name='viewtask',
            name='count_post_pday',
        ),
        migrations.RemoveField(
            model_name='votingtask',
            name='count_post_pday',
        ),
        migrations.AddField(
            model_name='reposttask',
            name='count_posts',
            field=models.IntegerField(null=True, verbose_name='кол-во публикаций'),
        ),
        migrations.AddField(
            model_name='reposttask',
            name='link_channel',
            field=models.URLField(default=None, max_length=120, verbose_name='ссылка на канал'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='viewtask',
            name='count_posts',
            field=models.IntegerField(null=True, verbose_name='кол-во публикаций'),
        ),
    ]
