# Generated by Django 4.1.3 on 2022-11-11 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_taskprices_alter_commenttask_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskprices',
            name='comment',
            field=models.IntegerField(default=0, verbose_name='Цена за комментарий'),
        ),
        migrations.AlterField(
            model_name='taskprices',
            name='reaction',
            field=models.IntegerField(default=0, verbose_name='Цена за реакцию'),
        ),
        migrations.AlterField(
            model_name='taskprices',
            name='repost',
            field=models.IntegerField(default=0, verbose_name='Цена за репост'),
        ),
        migrations.AlterField(
            model_name='taskprices',
            name='subscription',
            field=models.IntegerField(default=0, verbose_name='Цена за подписку'),
        ),
        migrations.AlterField(
            model_name='taskprices',
            name='views',
            field=models.IntegerField(default=0, verbose_name='Цена за просмотр'),
        ),
        migrations.AlterField(
            model_name='taskprices',
            name='vote',
            field=models.IntegerField(default=0, verbose_name='Цена за голосование'),
        ),
    ]
