# Generated by Django 4.1.3 on 2022-11-11 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_alter_taskprices_comment_alter_taskprices_reaction_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskprices',
            old_name='views',
            new_name='view',
        ),
        migrations.AlterField(
            model_name='taskprices',
            name='subscription',
            field=models.IntegerField(verbose_name='Цена за подписку'),
        ),
    ]
