# Generated by Django 4.1.3 on 2022-11-11 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_rename_views_taskprices_view_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskprices',
            name='subscription',
            field=models.IntegerField(default=0, verbose_name='Цена за подписку'),
        ),
    ]
