# Generated by Django 4.1.3 on 2022-11-11 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0010_alter_taskprices_comment_alter_taskprices_reaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskprices',
            name='reaction_sub',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=2, verbose_name='Цена за автореакцию'),
        ),
        migrations.AddField(
            model_name='taskprices',
            name='view_sub',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=2, verbose_name='Цена за автопросмотр'),
        ),
    ]
