# Generated by Django 4.1.3 on 2022-11-12 18:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0014_alter_taskprices_comment_alter_taskprices_reaction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commenttask',
            name='comments',
            field=models.TextField(verbose_name='комментарии (каждый с новой строки)'),
        ),
        migrations.AlterField(
            model_name='reactionstask',
            name='duration_sub',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(2, message='Подписка оформляется на минимум 2 дня.')], verbose_name='длительность подписки'),
        ),
        migrations.AlterField(
            model_name='reposttask',
            name='duration_sub',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(2, message='Подписка оформляется на минимум 2 дня.')], verbose_name='длительность подписки'),
        ),
        migrations.AlterField(
            model_name='viewtask',
            name='duration_sub',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(2, message='Подписка оформляется на минимум 2 дня.')], verbose_name='длительность подписки'),
        ),
        migrations.AlterField(
            model_name='votingtask',
            name='duration_sub',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(2, message='Подписка оформляется на минимум 2 дня.')], verbose_name='длительность подписки'),
        ),
    ]
